language: node_js
node_js:
  - 16
services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - export DOCKER_BUILDKIT=0
  - export COMPOSE_DOCKER_CLI_BUILD=0
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  #tagging
  - docker tag udagram-api-feed vladhoang/udagram-api-feed:v9
  - docker tag udagram-api-user vladhoang/udagram-api-user:v9
  - docker tag udagram-frontend vladhoang/udagram-frontend:v9
  - docker tag reverseproxy vladhoang/reverseproxy:v5
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vladhoang/udagram-api-feed:v5
  - docker push vladhoang/udagram-api-user:v5
  - docker push vladhoang/udagram-frontend:v5
  - docker push vladhoang/reverseproxy:v5
