language: node_js
node_js:
  - 16
services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - cd udagram-api-feed
  - docker build -t udagram-api-feed ./udagram-api-feed
  - cd ..
  - cd udagram-api-user
  - docker build -t udagram-api-user ./udagram-api-user
  - cd ..
  - cd udagram-frontend
  - docker build -t udagram-frontend ./udagram-frontend
  - cd ..
  - cd udagram-reverseproxy
  - docker build -t reverseproxy ./udagram-reverseproxy
  - cd ..
  #tagging
  - docker tag udagram-api-feed vladhoang/udagram-api-feed:v1
  - docker tag udagram-api-user vladhoang/udagram-api-user:v1
  - docker tag udagram-frontend vladhoang/udagram-frontend:v2
  - docker tag reverseproxy vladhoang/reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vladhoang/udagram-api-feed:v1
  - docker push vladhoang/udagram-api-user:v1
  - docker push vladhoang/udagram-frontend:v2
  - docker push vladhoang/reverseproxy:v1
