apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
      api: external
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
        - image: vladhoang/udagram-frontend:v10
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 400m
      #restartPolicy: Always
